### ISSUE TITLE
InvalidEntityStateException has useless message

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/base#265]
Right now the only useful information that is supplied to `InvalidEntityStateException` upon failed validation is the message class, e.g.:
```
io.spine.server.entity.InvalidEntityStateException: Entity state does match the validation constraints.. Message class: com.test.ExampleEntity. See Error.getValidationError() for details.
```

It worth including the validation error details into the message itself. Right now I have to `catch` the exception or debug tests to fish out the validation error details.

**Comment by alexander-yevsyukov** [comment]
While the exception `InvalidEntityStateException` belongs to `core-java`, the root cause of the problem belongs to this repository, and is in `ExceptionFactory.formatExceptionMessage()`.

The recent PR on code-generation improvements (#252) partially addressed the problem by including raw output of `ConstraintViolation`s. One of the near future PRs is going to provide human-readable text.

**Comment by dmdashenkov** [comment]
This is now resolved. The error message now includes the Exception message, the message type, and the formatted violation(s) message.
