### ISSUE TITLE
Messages with nested enums are not generated to JS

### ISSUE THREAD

**Issue by mdrachuk** [SpineEventEngine/base#277]
Right now the messages that contain enums do not generate the corresponding JS classes.

This is apparent in the generated `known_types.js`, which errors due to `null` class paths when loaded by the browser.

**Comment by armiol** [comment]
@dmitrykuzmin please have a look. This one may be done already.

**Comment by dmitrykuzmin** [comment]
This issue is no longer reproducible. 

The Proto JS plugin unit tests [verify](https://github.com/SpineEventEngine/base/blob/master/tools/proto-js-plugin/src/test/java/io/spine/js/generate/AppendTypeUrlGetterTest.java#L87) that the plugin itself works correctly in this case.

However, we could also consider adding smoke tests for the Proto JS plugin to ensure that the JS code generation process works correctly in general.
