### ISSUE TITLE
Why is `AbstractValidatingBuilder.internalBuild()` public?

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#72]
Do we use it somewhere outside? I did not find such usages in the generated code.

**Comment by armiol** [comment]
This method allows to obtain the current state of a message, even if the message violates the constraints. 

It [is used](https://github.com/SpineEventEngine/core-java/blob/951506604fe2c7c691236cbc2e331f2bc6921c32/server/src/main/java/io/spine/server/entity/Transaction.java#L346) in `Transaction` for two reasons:
* to log an invalid `Message` state if its validation fails;
* to feed the invalid `Message` state into `onRollback` listener.

Of course those calls are performed from outside of the `AbstractValidatingBuilder` package. That's why the method is marked `@Internal` and documented accordingly.

**Comment by armiol** [comment]
@alexander-yevsyukov FYI.
