### ISSUE TITLE
Make `spine_protoc.gradle` a valid script or avoid standard extension

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/base#84]
Problems with this file:
 * Underscore in the name. Other script we have uses dashes for word delimiters.
 * Even though file has `.gradle` extension it is not a valid Gradle script. 

This file is a template and IDEA complains on the syntax of template variables we use. Consider either renaming the file so that it doesn't have the standard extension. Or, transform the script so it takes arguments from a `.properties` file or another Gradle script.

**Comment by dmdashenkov** [comment]
As an option of how to fix this script, we may override the default template markers. Currently, the script receives arguments as follows:
```groovy
final def spineModelCompilerVersion = @baseVersion@
```
We may configure the template processor to work with `=null//` opening marker so that the line transforms into:
```groovy
final def spineModelCompilerVersion =null//baseVersion@
```

That way the IDE build-in compiler won't complain about the errors.

Another solution is to generate an additional configuration file and pass the arguments though it.

**Comment by alexander-yevsyukov** [comment]
Recent PRs changed the file name to have `.template` suffix. So this issue is not longer applicable.
